### ISSUE TITLE
ModuleNotFoundError: No module named 'rest_framework'

### ISSUE THREAD

**Issue by JenniferHem** [phi-grib/flame_API#15]
When trying to run the GUI I encounter the following error: 
```
PS C:\Users\HemmerJ3\Documents\Code\flame_API\flame_api> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
    self.run()
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\core\management\__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\site-packages\django\apps\config.py", line 228, in create
    import_module(entry)
  File "C:\Users\HemmerJ3\Programs\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
```
I installed the flame environment from the flame code repository and got an Error that Django is missing. After installing Django manually (version 4.0.3) I run into the error above. Am I using a wrong version of Django?

**Comment by manuelpastor** [comment]
We were unable to reproduce the error. Looks like the environment is not loaded before starting the command
