### ISSUE TITLE
rest_framework missing

### ISSUE THREAD

**Issue by nbosc** [phi-grib/flame_API#3]
After installing and activating the flame environment, when I run `python manage.py runserver`, I first get that django is missing. I installed django and now get:
```
Watching for file changes with StatReloader
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nbosc/flame_API/flame_api/flame_api/urls.py", line 29, in <module>
    url("manage/", include("manage.urls")),
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/nbosc/anaconda3/envs/flame/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nbosc/flame_API/flame_api/manage/urls.py", line 2, in <module>
    from .views import ListModels, ManageModels, ManageVersions, TestUpload, ManageParameters, ManageValidation
  File "/Users/nbosc/flame_API/flame_api/manage/views.py", line 4, in <module>
    from rest_framework.decorators import api_view
ModuleNotFoundError: No module named 'rest_framework'
```

**Comment by manuelpastor** [comment]
Please follow the recommended installation procedure:


>  Step 1. Install Flame
> 
> Go to the following page:
> 
> https://github.com/phi-grib/flame
> 
> and follow the Installation and Configuration instructions therein
> 
> Step 2. Install Flame_API
> 
> Go to the following page:
> 
> https://github.com/phi-grib/flame_API/
> 
> and follow the Installation instructions. Start the server.
> 
> Open a web browser and enter the following address:
> 
> http://localhost:8000

You must create the Flame environment (it was updated last week to include django and other required libraries), then install Flame, then call the API from within the same environment.

We will try to document this procedure better, thanks for pointing out this problem.
